# Generated by Django 3.2 on 2021-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('cost_time', models.CharField(max_length=40)),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('company', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=40)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('upload_time', models.CharField(max_length=20)),
            ],
        ),
    ]
