# Generated by Django 3.2 on 2021-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0002_cost_userinformation_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermark',
            name='filename',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='watermark',
            name='syspath',
            field=models.CharField(default='', max_length=30),
        ),
    ]
