# Generated by Django 3.2 on 2021-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0003_auto_20210415_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
