# Generated by Django 3.2 on 2021-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0004_alter_watermark_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
