# Generated by Django 3.2 on 2021-04-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0005_alter_cost_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='a',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='a',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='users',
            name='a',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='watermark',
            name='a',
            field=models.CharField(default='', max_length=16),
        ),
    ]
