# Generated by Django 3.2 on 2021-04-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0006_auto_20210419_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='a',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='a',
        ),
        migrations.RemoveField(
            model_name='users',
            name='a',
        ),
        migrations.RemoveField(
            model_name='watermark',
            name='a',
        ),
    ]
