# Generated by Django 3.2 on 2021-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarksys', '0008_auto_20210422_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='syspath',
            field=models.CharField(default='', max_length=60),
        ),
    ]
